## 100 numpy exercise を実際にやってみる

In [92]:
# 1. 読み込み
import numpy as np
# 2. バージョンとコンフィグの確認
print("2:\n",np.__version__)
np.show_config()

2:
 1.11.1
openblas_lapack_info:
  NOT AVAILABLE
blas_opt_info:
    include_dirs = ['C:\\Minonda\\envs\\_build\\Library\\include']
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['C:\\Minonda\\envs\\_build\\Library\\lib']
blas_mkl_info:
    include_dirs = ['C:\\Minonda\\envs\\_build\\Library\\include']
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['C:\\Minonda\\envs\\_build\\Library\\lib']
mkl_info:
    include_dirs = ['C:\\Minonda\\envs\\_build\\Library\\include']
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['C:\\Minonda\\envs\\_build\\Library\\lib']
lapack_mkl_info:
    include_dirs = ['C:\\Minonda\\envs\\_build\\Library\\include']
  

In [93]:
# 3. サイズ10の0ベクトルを作る
a3 = np.zeros(10)
print("3:\n",a3)
# 4. 配列のメモリサイズを確認する
print("4: {}".format(a3.size*a3.itemsize))
# 6. サイズが10で5番目の値だけ1の配列を作る
a6 = np.zeros(10)
a6[4] = 1
print("6:\n",a6)
# 7. 値が10から49まで順に並んだ配列を作る
a7 = np.arange(10,50)
print("7:\n",a7)
# 8. 配列の値をひっくり返す
a8 = a7[::-1]
print("8:\n",a8)
# 9. それぞれ0~8まで入った3×3の行列を作る
A9 = np.arange(0,9).reshape(3,3)
print("9:\n",A9)

# 10. [1,2,0,0,4,0]から0じゃない箇所を見つける
tmp = np.array([1,2,0,0,4,0])
# 自分の回答
index = []
for i, el in enumerate(tmp):
    if el != 0:
        index.append(el)
print("10:\n", index)
# 模範解答
nz = np.nonzero(tmp)
print("10:\n",nz)
# 11. 3×3の単位行列をつくる
# 自分の回答
A11 = np.zeros((3,3))
for i in range(3):
    A11[i][i] = 1
print("11:\n", A11)
# 模範解答
A11 = np.eye(3)
print("11:\n", A11)

# 12. 3×3×3の乱数行列を作る
A12 = np.random.random((3,3,3))
print("12:\n", A12)

# 13 10×10の乱数行列を作って、最大値と最小値を見つける
A13 = np.random.random((10,10))
print("13: min:{}, max:{}".format(A13.min(), A13.max()))

# 14 サイズ30の乱数ベクトルを作って平均値を出す
a14 = np.random.random(30)
print("14: mean :\n",a14.mean())

# 15 境界が1で、中身が0の2次元配列をつくる
# 自分の回答
N = 4
A15 = np.zeros((N,N))
A15[0,:] = 1
A15[-1,:] = 1
A15[:,0] = 1
A15[:,-1] = 1
print("15:\n", A15)
#模範解答
A15 = np.ones((N,N))
A15[1:-1,1:-1] = 0
print("15:\n", A15)

# 16. 今ある配列に、0で埋めた境界を作る
A16 = np.ones((N,N))
A16 = np.pad(A16, pad_width=1, mode='constant', constant_values=0)
print("16:\n", A16)

3:
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
4: 80
6:
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
7:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
8:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
9:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
10:
 [1, 2, 4]
10:
 (array([0, 1, 4], dtype=int64),)
11:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
11:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
12:
 [[[ 0.91618022  0.48931849  0.08745434]
  [ 0.43850921  0.70384563  0.87525467]
  [ 0.99291867  0.13650006  0.37122659]]

 [[ 0.72861529  0.07841201  0.4305913 ]
  [ 0.83348395  0.61879131  0.17332209]
  [ 0.96673959  0.6003669   0.36313724]]

 [[ 0.49511295  0.52185943  0.76325218]
  [ 0.63367539  0.36681963  0.34302854]
  [ 0.67441809  0.25902874  0.14086399]]]
13: min:0.005605751017701777, max:0.9920108090163369
14: mean :
 0.425400424509
15:
 [[ 1.

In [95]:
# 17. 下記の結果はどうなる？
print("17;")
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

17;
nan
False
False
nan
False


In [96]:
# 18. 5×5の行列を作って、対角成分の一つ下だけ1,2,3,4で埋める
# 自分の回答
A18 = np.zeros((5,5))
for i in range(1,5):
    A18[i][i-1] = i
print("18:\n",A18)
# 模範解答
A18 = np.diag(1+np.arange(4),k=-1)
print("18:\n",A18)
# 19. 8×8の行列を作り、チェッカーボードパターンを作る
A19 = np.zeros((8,8))
A19[1::2,::2] = 1
# A19[::2,1::2] = 1
print("19:\n", A19)
# 20. (6,7,8)の配列で、インデックス(x,y,z)における100番目の要素は？
print("20:\n",np.unravel_index(100,(6,7,8)))
# 21. tile functionを使って8×8のチェッカーボードパターンを作る
A21 = np.tile(np.array([[0,1],[1,0]]),(4,4))
print("21:\n", A21)

18:
 [[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]
18:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
19:
 [[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]
20:
 (1, 5, 4)
21:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [187]:
# 22.5×5の乱数行列を正規化する
A22 = np.random.random((5,5))
minimum, maximum = A22.min(), A22.max()
print("22:\n",(A22-minimum)/(maximum-minimum))
# 23. 8ビット整数(ubyte)を使って色を記述するdtypeを作る
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print("23:\n",color)
# 24. 5×3の行列と3×2の行列を掛け合わせる(実数)
A24 = np.arange(0,15).reshape(5,3)
B24 = np.arange(0,6).reshape(3,2)
print("24:\n",np.dot(A24,B24))
# その他の回答
print("24:\n",A24@B24)
# 25. 1次元配列で、3以上8以下の値は負値にする
a25 = np.arange(15)
a25[(a25>3)&(a25<=8)] *= -1
print("25:\n",a25)

# 26. numpy有無でのsum()の結果はわかる？
print("26:")
# print(sum(range(5),-1))　#9
from numpy import *
print(sum(range(5),-1)) #10

# 27. 整数ベクトルのなかでどの記述が間違っている？
a27 = np.arange(5)
print("a27:\n",a27)
print(a27**a27)#行列の要素^(行列の要素)
print(2 << a27 >> 2)#シフト？
print(a27 <- a27)
print(1j*a27) #複素数
print(a27/1/1)

# print(Z<Z>Z) The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# 28 次の結果を予想しなさい
print("28:")
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0)) #a//b : 切り捨て除算
print(np.array([np.nan]).astype(int).astype(float))

# 29 小数点以下切り上げの配列に変える
a29 = np.random.uniform(-10,10,10) #-10から10のサイズ10の一様乱数
print("29:")
print(a29)
# 自分の回答
for i,el in enumerate(a29):
    if el < 0:
        a29[i] = np.floor(el)
    else:
        a29[i] = np.ceil(el)
print(a29)
# 模範解答 copysignってのがあるのか
print (np.copysign(np.ceil(np.abs(a29)), a29))

# 30. 2つの配列の中から同じ値を見つける
# intersectを使う
a30_1 = np.arange(0,10)
a30_2 = np.arange(0,20,2)
print("30:\n",np.intersect1d(a30_1,a30_2))

# 31. numpyのwarningを無視する
env = np.seterr(all="ignore") #無視
np.seterr(**env) #戻す
#32.np.sqrtとnp.emath.sqrtの違い
# emathをいれると複素数まで拡張される
print("32:")
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

22:
 [[ 0.46040708  0.60243909  0.13287689  0.53072832  1.        ]
 [ 0.          0.66434133  0.77137762  0.18876591  0.42399966]
 [ 0.09759486  0.07121624  0.57746737  0.88507219  0.47221302]
 [ 0.54660799  0.43114544  0.78649443  0.71106225  0.48850214]
 [ 0.02885411  0.83854647  0.35975913  0.83940063  0.39800443]]
23:
 [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
24:
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
24:
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
25:
 [ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]
26:
10
a27:
 [0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[ 0.+0.j  0.+1.j  0.+2.j  0.+3.j  0.+4.j]
[ 0.  1.  2.  3.  4.]
28:
nan
0
[ -2.14748365e+09]
29:
[ 8.7081472  -0.90801661  1.08439237 -8.86407971 -6.87943859  8.21560051
  0.69206394  2.11392746  2.70739731 -7.0265742 ]
[ 9. -1.  2. -9. -7.  9.  1.  3.  3. -8.]
[ 9. -1.  2. -9. -7.  9.  1.  3.  3. -8.]
30:
 [0 2 4 6 8]
32:
nan


In [204]:
# 33. 昨日、今日、明日の日付
# datetimeで良くない？
# datetime64型なのね
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
# 34. 2016年7月の配列
a34 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("34:\n",a34)
print(type(a34[0]))
# 35 ((A+B)*(-A/2))をコピーなしで計算
a35 = np.ones(5)
b35 = np.ones(5)*2
np.add(a35, b35, out=b35)
np.divide(a35,2,out=a35)
c35= np.multiply(a35,b35,out=a35)
print("35:\n",c35)

34:
 ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
<class 'numpy.datetime64'>
35:
 [ 1.5  1.5  1.5  1.5  1.5]


In [237]:
# 36. 乱数行列の整数部分だけ取り出すやつ5種類
Z = np.random.uniform(0,10,10)
print("36:")
print(Z - Z%1) #余りを引く
print(np.floor(Z)) # 切り捨ての関数
print(np.ceil(Z)-1) # 切り上げて1を引く
print(Z.astype(int).astype(float)) #整数にしちゃう
print(np.trunc(Z)) #整数部だけ取り出す
print(Z//1) # 切り捨て演算子

# 37. 行の値が[0,1,2,3,4]となる、5×5の行列
a37 = np.zeros((5,5))
a37 += np.arange(5)
print("37:\n",a37)

# 38. ジェネレータを使って0から9までの配列を作る
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.fromiter.html
def generate():
    for x in range(10):
        yield x
a38 = np.fromiter(generate(),dtype=float,count=-1)
print("38:\n",a38)

#39. 0より大、１より小のサイズ10のrangingベクトルを作る
# 自分の回答
a39 = np.linspace(0,1,12)[1:-1]
# 模範回答 : endpointオプション
a39 = np.linspace(0,1,11,endpoint=False)[1:]
print("39:\n",a39)

# 40. サイズ10のランダム配列を作ってsortする
print("40:")
a = np.random.random(10)
print(a)
a.sort()
print(a)

36:
[ 5.  7.  5.  8.  4.  9.  2.  6.  3.  2.]
[ 5.  7.  5.  8.  4.  9.  2.  6.  3.  2.]
[ 5.  7.  5.  8.  4.  9.  2.  6.  3.  2.]
[ 5.  7.  5.  8.  4.  9.  2.  6.  3.  2.]
[ 5.  7.  5.  8.  4.  9.  2.  6.  3.  2.]
[ 5.  7.  5.  8.  4.  9.  2.  6.  3.  2.]
37:
 [[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]
38:
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
39:
 [ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]
40:
[ 0.22006689  0.55178619  0.63263176  0.8987876   0.359807    0.50134362
  0.88579329  0.22264231  0.83544229  0.30953192]
[ 0.22006689  0.22264231  0.30953192  0.359807    0.50134362  0.55178619
  0.63263176  0.83544229  0.88579329  0.8987876 ]


In [300]:
# 41. 小さい行列をnp.sumより早く計算する方法は？
# add.reduceを使う
print("41:")
a41 = np.arange(100)
print(np.add.reduce(a41))
#42. 2つのランダムベクトルが等しいかどうかを判定する
print("42:")
A42 = np.random.randint(0,2,2)
B42 = np.random.randint(0,2,2)
print(A42,B42)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A42,B42)
print(equal)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A42,B42)
print(equal)

# 43. 配列をimmutable(read-only)にする
# writeable
a43 = np.zeros(10)
a43.flags.writeable = False
# a43[0] = 1 エラーが出る

# 44. 直交座標の10×2の行列を極座標変換
a44 = np.random.random((10,2))
x,y = a44[:,0], a44[:,1]
r = np.sqrt(x**2+y**2)
theta = np.arctan(y/x)
print("44:\n",np.vstack((r,theta)).T)

# 45. サイズ10のベクトルを作って最大値を0に変換
a45 = np.random.random(10)
print("45:\n",a45)
a45[a45.argmax()] = 0
print(a45)

# 46. x,y座標を[0,1]×[0,1]領域に変換したstructured arrayを作る
# meshgridと、keyを持たせる方法
# https://deepage.net/features/numpy-meshgrid.html
A46 = np.zeros((5,5), [('x',float),('y',float)])
A46['x'], A46['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print("46:\n",A46)

# 47. 2つのベクトルを用いてコーシー配列(Cij =1/(xi - yj))を作れ
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ufunc.outer.html
x = np.arange(1,5)+0.1
y = np.arange(1,5)
# ダメ C = 1.0 / (x-y)
C = 1.0 / np.subtract.outer(x, y)
print("47:\n",C)

# 48. それぞれのnumpy scalar typeでの最小、最大値をprintする
# int typeの違い
inttypes = [np.int8, np.int32, np.int64]
floattypes = [np.float32, np.float64]
# 計算機epsilon https://ja.wikipedia.org/wiki/%E8%A8%88%E7%AE%97%E6%A9%9F%E3%82%A4%E3%83%97%E3%82%B7%E3%83%AD%E3%83%B3
for dtype in inttypes:
    print("{} min : {}".format(dtype,np.iinfo(dtype).min))
    print("{} max : {}".format(dtype,np.iinfo(dtype).max))
for dtype in floattypes:
    print("{} min : {}".format(dtype,np.finfo(dtype).min))
    print("{} max : {}".format(dtype,np.finfo(dtype).max))
    print("{} eps : {}".format(dtype,np.finfo(dtype).eps))
    
# 49. 配列の全ての値を省略せずにプリントする
# printoptionsの利用 https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.set_printoptions.html
np.set_printoptions(threshold=np.nan)
A49 = np.zeros((16,16))
print("A49:\n",A49)

41:
4950
42:
[1 0] [1 1]
False
False
44:
 [[ 0.54414931  0.02466314]
 [ 0.95336779  1.01449172]
 [ 0.81330035  0.05810492]
 [ 0.83047189  0.41162947]
 [ 0.73405429  0.76321812]
 [ 0.82535396  1.17736737]
 [ 0.29751909  1.40374262]
 [ 0.98727458  0.06481007]
 [ 0.98852828  0.75045656]
 [ 0.63889285  0.40355561]]
45:
 [ 0.73523658  0.74313153  0.55629703  0.27443126  0.33492972  0.29801676
  0.2071832   0.80891655  0.85658349  0.19785022]
[ 0.73523658  0.74313153  0.55629703  0.27443126  0.33492972  0.29801676
  0.2071832   0.80891655  0.          0.19785022]
46:
 [[(0.0, 0.0) (0.25, 0.0) (0.5, 0.0) (0.75, 0.0) (1.0, 0.0)]
 [(0.0, 0.25) (0.25, 0.25) (0.5, 0.25) (0.75, 0.25) (1.0, 0.25)]
 [(0.0, 0.5) (0.25, 0.5) (0.5, 0.5) (0.75, 0.5) (1.0, 0.5)]
 [(0.0, 0.75) (0.25, 0.75) (0.5, 0.75) (0.75, 0.75) (1.0, 0.75)]
 [(0.0, 1.0) (0.25, 1.0) (0.5, 1.0) (0.75, 1.0) (1.0, 1.0)]]
47:
 [[ 10.          -1.11111111  -0.52631579  -0.34482759]
 [  0.90909091  10.          -1.11111111  -0.52631579]
 [  0

In [369]:
# 50. ベクトル内の与えられたvalueの中で最も近い値を出力
value = 3
a50 = np.random.random(30)*10
print("50:\n",a50)  
print(a50[np.abs(a50-value).argmin()])

# 51. 位置座標とcolorのRGBが保存されたstructured arrayを作る
A51 = np.zeros(10, [("coordinate",[("x",float),("y",float),("z",float)]),
                    ("color",[("r",float),("g",float),("b",float)])])
print("51:\n",A51)

# 52. 10×2のランダム行列を作って、点同士の距離を求める
# 自分の回答
A52 = np.random.random((10,2))
def dist(v1, v2):
    return np.sqrt((v1[0]-v2[0])**2+(v1[1]-v2[1])**2)
D52 = np.zeros((len(A52),len(A52)))
for i in range(len(A52)):
    for j in range(len(A52)):
        D52[i][j] = dist(A52[i],A52[j])
print("52:\n",D52)
# 模範解答
X,Y = np.atleast_2d(A52[:,0], A52[:,1])
D52 = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print("52 mohan:\n",D52)

# 53. float32の行列をint32の行列に変換
a53 = np.arange(10, dtype=np.float32)
a53 = a53.astype(np.int32, copy=False)
print("53:\n",a53)

# 54. どうやってファイルを配列に変換する？
# pandasで良くない？
from io import StringIO
# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
# Z = np.genfromtxt(s, delimiter=",", dtype=np.int)

# 55. numpyの配列のenumerateと同等の表現は？
# ndenumerate, ndindex
A55 = np.arange(9).reshape(3,3)
print("55:\n",A55)
for index, value in np.ndenumerate(A55):
    print(index, value)
for index in np.ndindex(A55.shape):
    print(index, A55[index])
    
# 56. 2DのGaussian-like arrayを生成する
X, Y = np.meshgrid(np.linspace(-1,1,6),np.linspace(-1,1,6))
D= np.sqrt(X**2+Y**2)
sigma, mu = 1.0, 0
G56 = np.exp(-((D-mu)**2)/2*sigma**2)
print("56:\n",G56)

# 57. 2次元配列にランダムにp個、値を埋め込む
# np.putとnp.random.choice
p = 10
A57 = np.zeros((10,10))
np.put(A57, np.random.choice(range(n*n), p, replace=False),1)
print("57:\n",A57)

# 58. 行列の各行に対し、その行の平均を引いていく
A58 = np.arange(16).reshape(4,4)
print("58:\n",A58-A58.mean(axis=1,keepdims=True))

# 59. n列目のcolomunをソート
n59 = 2
A59 = np.random.random((4,4))
print("59:\n",A59)
print(A59[:,n59].argsort())

50:
 [ 4.16137626  8.00011802  0.37452151  4.48251317  9.59850527  7.22191011
  6.78959842  5.16099055  7.51769683  4.61913486  9.09240623  7.34474354
  7.89478829  7.46509129  5.26764795  0.85136358  4.40700183  5.09933914
  1.07700298  5.75686635  4.06709496  5.87563881  5.98861015  1.05394858
  6.25655182  3.60596326  5.28338047  7.54686264  6.73301092  3.1450267 ]
3.14502670107
51:
 [((0.0, 0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))]
52:
 [[ 0.          0.59671401  0.49014599  0.27081722  0.62455669  0.45638502
   0.57072376  0.38490642  0.50973025  0.76700968]
 [ 0.59671401  0.          0.20282351  0.74168089  0.72016588  0.9057764
   0.34498348  0.76270755  0.94269902  0.84856851]


In [385]:
# 60. 2D arrayにnullがあるかどうかを判定する
# any https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.any.html
A60 = np.random.randint(0,3,(5,5))
print("60:")
print(A60)
print((~A60.any(axis=0)).any())
# 61. 指定の値に最も近い値を見つける
# 50と一緒

# 62. イテレータを使って1×3行列と3×1行列のsumを計算
print("62:")
A62 = np.arange(3).reshape(3,1)
B62 = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

# 63, 名前の属性を付与したarrayクラスをつくる
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
A63 = NamedArray(np.arange(10), "range_10")
print ("A63:\n",A63.name,A63)

60:
[[0 1 2 2 2]
 [1 1 1 1 0]
 [2 1 1 1 2]
 [2 0 0 0 1]
 [1 2 0 2 2]]
False
62:
[[0 1 2]
 [1 2 3]
 [2 3 4]]
A63:
 range_10 [0 1 2 3 4 5 6 7 8 9]
