## numpy 100 exercises (上級編)

In [1]:
import numpy as np

In [2]:
# 64. ２つのベクトルa,bがあって、aベクトルに、bで与えられたインデックスに箇所に1を加える
# 自分の回答
a = np.ones(10)
b = np.random.randint(0,10,5)
print("64:")
print(a,b)
for el in b:
    a[el] += 1
print(a)
# 模範解答
# 1. bitcountを使う方法
a = np.ones(10)
a += np.bincount(b, minlength=len(a))
print(a)
# 2. np.add.atを使う
a = np.ones(10)
np.add.at(a,b,1)
print(a)

# 65. aベクトルの値を用いて新しいベクトルを、bのインデックスに従って作る
print("65:")
a = np.arange(10)
b = np.random.randint(0,10,10)
print(a,b)
print(np.bincount(b,a))

# 66. (dtype=ubyte)の(w,h,3)画像全体を定義し、uniqueな値の数計算する(色はRGB256階調)
# np.unique(F)は、uniqueな値の配列を返す(setみたいなもの)
print("66:")
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
# print(I[:,:,0])とprint(I[...,0])は同義

F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
print(np.unique(F))
n = len(np.unique(F))
print(n)

# 67, 4次元配列において、最後の2軸だけ一気に足す方法は？
print("67:")
A = np.random.randint(0,5,(2,2,2,2))
print(A)
B = A.sum(axis=(-1,-2))
print(B)
# 別解
print(A.reshape(A.shape[:-2]+(-1,)).sum(axis=-1))

# 68. 1次元ベクトルaを用意する。aと同じサイズで用意されたインデックスベクトル(min:0, max:9) s に従って構成されるsubsetベクトルの平均を求めよ
print("68:")
# 自分の回答
a = np.random.random(100)
s = np.random.randint(0,10,100)
c = np.zeros(10)
for (v,el) in zip(a,s):
    c[el] += v
print(c/np.bincount(s))
# 模範解答(pandas使う)
import pandas as pd
print(pd.Series(a).groupby(s).mean())
# bitcount等
D_sums = np.bincount(s, weights=a)
D_counts = np.bincount(s)
D_means = D_sums / D_counts
print(D_means)

"""
bincount便利
axisは何個か指定できる
np.uniqueもなかなか便利
"""

64:
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.] [7 5 5 1 7]
[ 1.  2.  1.  1.  1.  3.  1.  3.  1.  1.]
[ 1.  2.  1.  1.  1.  3.  1.  3.  1.  1.]
[ 1.  2.  1.  1.  1.  3.  1.  3.  1.  1.]
65:
[0 1 2 3 4 5 6 7 8 9] [3 6 4 0 6 6 8 2 6 5]
[  3.   0.   7.   0.   2.   9.  18.   0.   6.]
66:
[    0     1   256   257 65536 65537 65792 65793]
8
67:
[[[[2 4]
   [2 1]]

  [[3 3]
   [1 4]]]


 [[[0 2]
   [1 0]]

  [[0 0]
   [4 2]]]]
[[ 9 11]
 [ 3  6]]
[[ 9 11]
 [ 3  6]]
68:
[ 0.44387462  0.68917607  0.40017462  0.53827246  0.54355924  0.3649502
  0.4041567   0.30498644  0.42523012  0.38898766]
0    0.443875
1    0.689176
2    0.400175
3    0.538272
4    0.543559
5    0.364950
6    0.404157
7    0.304986
8    0.425230
9    0.388988
dtype: float64
[ 0.44387462  0.68917607  0.40017462  0.53827246  0.54355924  0.3649502
  0.4041567   0.30498644  0.42523012  0.38898766]


'\nbincount便利\naxisは何個か指定できる\nnp.uniqueもなかなか便利\n'

In [3]:
# 69. 内積の対角成分だけを取り出す
print("69:")
A = np.random.randint(0,5,(3,3))
B = np.random.randint(0,5,(3,3))
print(np.diag(np.dot(A,B)))
# もっと早いver.(うまく計算を利用)
print(np.sum(A*B.T, axis=1))
# もっともっと早いver.(einsum)
print(np.einsum("ij,ji->i",A,B))
# 70. [1,2,3,4,5]に対し、各値の間に3つの連続したゼロが挿入された新しいベクトルを作成する方法は？
a = np.array([1,2,3,4,5])
nz = 3
a0 = np.zeros((len(a)-1)*nz+len(a))
a0[::nz+1] = a
print(a0)

69:
[27 14  0]
[27 14  0]
[27 14  0]
[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


In [4]:
#71. (5,5,3)の行列に対し、(5,5)の行列を、(5,5)の要素の箇所だけ掛け合わせる方法は？
print("71:")
# 自分の回答
A = np.random.random((5,5,3))
B = np.arange(25).reshape((5,5))
print(np.einsum("ijk,ij->ijk",A,B))
# 模範解答
print(A * B[:,:,None])

# 72. 行列の特定の行を入れ替える
print("72:")
# 自分の回答
A = np.arange(9).reshape(3,3)
print(A)
B = A.copy()
B[0] = A[1]
B[1] = A[0]
print(B)
# 模範解答 こういう操作も出来るのか。。。
A[[1,0]] = A[[0,1]]
print(A)

71:
[[[  0.           0.           0.        ]
  [  0.37711233   0.29788396   0.6237702 ]
  [  0.19079381   1.76324126   0.08257048]
  [  2.21989008   2.26374423   1.86255598]
  [  1.2665843    2.98892828   1.59862483]]

 [[  1.7780537    0.46065768   2.65405354]
  [  0.2611062    5.17039702   2.279674  ]
  [  0.80172058   6.46268009   6.24431357]
  [  4.8722276    4.57574313   0.87361167]
  [  6.63257263   6.19201498   0.56549781]]

 [[  9.04995866   2.08395426   9.04987017]
  [  6.95529155   7.0347296    3.50166894]
  [  7.40999719   5.99490976  10.26948179]
  [  1.73706829  12.83350862   4.13489235]
  [  3.95179633  11.85583287   5.16652135]]

 [[  9.4794708    4.29748085   2.10243884]
  [  6.21938886   4.62678618  11.58889152]
  [  3.75976111   4.97639448  16.0916132 ]
  [  2.66524022   5.2966464    0.6592274 ]
  [  0.38407869   9.21434732   5.08633179]]

 [[  8.38913975   1.82528893   8.60033277]
  [  9.08500939   9.53280782  10.00344974]
  [  9.58605057   1.76554449  12.14161475]

In [5]:
# 73, 三角形を記述する10個のtripletsがある。全ての三角形を作る線分の中で、uniqueなモノを書き出す。
print("73:")
faces = np.random.randint(0,100,(10,3))
print(faces)
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print(F)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
print(F)
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.view.html
G = F.view(dtype=[('p0',F.dtype),('p1',F.dtype)] )
print(G)
G = np.unique(G)
print(G)

73:
[[69 50 23]
 [39 26 14]
 [51 80 11]
 [15 81  4]
 [47 11 43]
 [67 30 91]
 [53 71 76]
 [94 71 95]
 [90 74 87]
 [33 11 46]]
[[69 50 50 23 23 69]
 [39 26 26 14 14 39]
 [51 80 80 11 11 51]
 [15 81 81  4  4 15]
 [47 11 11 43 43 47]
 [67 30 30 91 91 67]
 [53 71 71 76 76 53]
 [94 71 71 95 95 94]
 [90 74 74 87 87 90]
 [33 11 11 46 46 33]]
[[50 69]
 [23 50]
 [23 69]
 [26 39]
 [14 26]
 [14 39]
 [51 80]
 [11 80]
 [11 51]
 [15 81]
 [ 4 81]
 [ 4 15]
 [11 47]
 [11 43]
 [43 47]
 [30 67]
 [30 91]
 [67 91]
 [53 71]
 [71 76]
 [53 76]
 [71 94]
 [71 95]
 [94 95]
 [74 90]
 [74 87]
 [87 90]
 [11 33]
 [11 46]
 [33 46]]
[[(50, 69)]
 [(23, 50)]
 [(23, 69)]
 [(26, 39)]
 [(14, 26)]
 [(14, 39)]
 [(51, 80)]
 [(11, 80)]
 [(11, 51)]
 [(15, 81)]
 [(4, 81)]
 [(4, 15)]
 [(11, 47)]
 [(11, 43)]
 [(43, 47)]
 [(30, 67)]
 [(30, 91)]
 [(67, 91)]
 [(53, 71)]
 [(71, 76)]
 [(53, 76)]
 [(71, 94)]
 [(71, 95)]
 [(94, 95)]
 [(74, 90)]
 [(74, 87)]
 [(87, 90)]
 [(11, 33)]
 [(11, 46)]
 [(33, 46)]]
[(4, 15) (4, 81) (11, 33) (11, 43)

In [7]:
# 74, bincountされた配列Cに対して、np.bincount(A)==CとなるようなAをどう作るか
# np.repeat : https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.repeat.html: 
print("74:")
C = np.bincount([1,2,3,3,2,4])
print(C)
A = np.repeat(np.arange(len(C)),C)
print(A)

# 75. array上でsliding windowを使った平均算出法
# pandasで良くない？
# 自分の回答
print("75:")
a = np.arange(30)
window = 10
b = np.zeros(len(a))
for i in range(len(a)):
    if i == 0:
        b[i] = a[i]
    elif i < 10:
        b[i] = a[:i+1].mean()
    else:
        b[i] = a[i-10+1:i+1].mean()
print(b)
# 模範解答 : cumsum
# cumsum https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cumsum.html
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
print(moving_average(a,window))

# 76. 一次元ベクトルaに対して一行目が(a[0],a[1],a[2])となって、以下の行はインデックスを1ずつずらした値が入るような行列をつくるう
# numpy.lib.stride_tricksの利用
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.lib.stride_tricks.as_strided.html
print("76:")
a = np.arange(10)
def rolling(a, window):
    shape = (a.size-window+1,window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
A = rolling(a,5)
print(A)

# 77. booleanをひっくり返す、floatの記号をひっくり返す
# logical_not, negativeという関数
print("77:")
a = np.random.randint(0,2,10)
print(a)
np.logical_not(a, out=a)
print(a)
a = np.random.uniform(-1.0,1.0,10)
print(a)
np.negative(a, out=a)
print(a)

74:
[0 1 2 2 1]
[1 2 2 3 3 4]
75:
[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.5   6.5
   7.5   8.5   9.5  10.5  11.5  12.5  13.5  14.5  15.5  16.5  17.5  18.5
  19.5  20.5  21.5  22.5  23.5  24.5]
[  4.5   5.5   6.5   7.5   8.5   9.5  10.5  11.5  12.5  13.5  14.5  15.5
  16.5  17.5  18.5  19.5  20.5  21.5  22.5  23.5  24.5]
76:
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]
77:
[1 1 1 0 0 0 0 1 0 0]
[0 0 0 1 1 1 1 0 1 1]
[-0.55817305 -0.70925185 -0.77976949  0.60214446  0.56847229 -0.43234043
  0.16153943 -0.04372468  0.45307838 -0.02448935]
[ 0.55817305  0.70925185  0.77976949 -0.60214446 -0.56847229  0.43234043
 -0.16153943  0.04372468 -0.45307838  0.02448935]


In [ ]:
# 81. a=[1,2,3,4,5,...,14]とした時、R = [[1,2,3,4],[2.3.4.5].[3.4.5.6],...,[11,12,13,14]]を作る方法
# 自分の回答
a = np.arange(1,15,dtype=np.int32)
b = np.zeros((11,4),dtype=np.int32)
for i in range(11):
    b[i] = a[i:i+4]
print(b)
# 模範解答
# np.lib.straide_tricks 
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.lib.stride_tricks.as_strided.html
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# 82. 行列のランクを計算する
print("82:")
# 線形代数パッケージlinalg()を使う 
# (https://pythondatascience.plavox.info/numpy/%E7%B7%9A%E5%BD%A2%E4%BB%A3%E6%95%B0)
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# 83. 行列の中で最も使われている値を見つける
print("83:")
A = np.random.randint(0,5,10)
print(A)
print(np.bincount(A).argmax())

# 84. (10,10)のランダム行列から全ての連続した(3,3)行列を取り出す
print("84:")
A = np.random.random((10,10))
# print(A)
C = np.zeros((A.shape[0]-3,A.shape[1]-3,3,3))
for i in range(A.shape[0]-3):
    for j in range(A.shape[1]-3):
       print(A[i:i+3,j:j+3])
# 模範解答　libのstrideを使う
n = 3
i = 1 + (A.shape[0]-3)
j = 1 + (A.shape[1]-3)
C = np.lib.stride_tricks.as_strided(A, shape=(i, j, n, n), strides=A.strides + A.strides)

In [ ]:
# 89. 配列の中でn番目に大きな値を取る
print("89:")
n = 5
a = np.random.randint(0,100,10)
print(a)
print(a[a.argsort()[-n:]])
# もっと早い
print(a[np.argpartition(-a,n)[:n]])

In [ ]:
# 92. 大きなベクトルaに対し、aの要素を3乗する計算方法を3つ答えよ
# 各手法の計算時間を算出してくれている
x = np.random.rand(5e7)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

In [ ]:

# 94. (10,3)の行列に対し、全て異なるrowとなるmatrix
# np.all https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.all.html
# 模範解答
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(A[:,1:] == A[:,:-1], axis=1)
U = A[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = A[A.max(axis=1) != A.min(axis=1),:]
print(U)

# 95. 
# 96. 2次元配列において、uniqueなrowを抽出
print("96:")
A = np.random.randint(0,5,(10,2))
# 模範解答
# ascontiguousarray
# view
T = np.ascontiguousarray(A).view(np.dtype((np.void, A.dtype.itemsize * A.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = A[idx]
print(uZ)